### ISSUE TITLE
How to get total step done value for the current training instance?

### ISSUE THREAD

**Issue by Marioando** [idiap/coqui-ai-Trainer#15]
Hello!
How to get total step done value , I know there is self.total_steps_done for trainer but as far as I know it pick up all steps from previous training if you restore a model , what I want is to get the value of current training steps done wihout adding the restored step. I mean I restore model from 10k. Total step done should start from 0 not 10k . Thank you for your help

**Comment by eginhard** [comment]
Haven't looked at the details, but I think subtracting `restore_step` from `total_steps_done` should give you what you want.
